apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- 00-namespace.yaml
- 01-deployment.yaml
- 02-service.yaml
- 03-hpa.yaml
- 04-ingress.yaml
namespace: app-2
images:
- name: mauriciopgomes/app-2
  newName: mauriciopgomes/app-2
  newTag: be4f87f8cc72b3054411bb97038e4cf9c2df2dd6
