apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- 00-namespace.yaml
- 01-deployment.yaml
- 02-service.yaml
- 03-hpa.yaml
- 04-ingress.yaml
namespace: app-2
images:
- name: mauriciopgomes/app-2
  newName: mauriciopgomes/app-2
  newTag: 63b8a42efe4ded4c37099c3ee4b3ff5192d99a31
